wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720659962.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.12.4
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
lr:
  desc: null
  value: 0.0001
opt:
  desc: null
  value: adam
resume:
  desc: null
  value: false
noaug:
  desc: null
  value: true
noamp:
  desc: null
  value: false
nowandb:
  desc: null
  value: false
mixup:
  desc: null
  value: false
net:
  desc: null
  value: vit_small
dp:
  desc: null
  value: false
bs:
  desc: null
  value: '512'
size:
  desc: null
  value: '32'
n_epochs:
  desc: null
  value: 200
patch:
  desc: null
  value: 4
dimhead:
  desc: null
  value: 512
convkernel:
  desc: null
  value: 8
